config/routes.rb
Rails.application.routes.draw do
  resources :hellos

end

app/models/hello.rb
class Hello < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hellos_controller.rb
class HellosController < ApplicationController
  before_action :set_hello, only: [:show, :edit, :update, :destroy]

  # GET /hellos
  # GET /hellos.json
  def index
    @hellos = Hello.all
  end

  # GET /hellos/1
  # GET /hellos/1.json
  def show
  end

  # GET /hellos/new
  def new
    @hello = Hello.new
  end

  # GET /hellos/1/edit
  def edit
  end

  # POST /hellos
  # POST /hellos.json
  def create
    @hello = Hello.new(hello_params)

    respond_to do |format|
      if @hello.save
        format.html { redirect_to @hello, notice: 'Hello was successfully created.' }
        format.json { render :show, status: :created, location: @hello }
      else
        format.html { render :new }
        format.json { render json: @hello.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hellos/1
  # PATCH/PUT /hellos/1.json
  def update
    respond_to do |format|
      if @hello.update(hello_params)
        format.html { redirect_to @hello, notice: 'Hello was successfully updated.' }
        format.json { render :show, status: :ok, location: @hello }
      else
        format.html { render :edit }
        format.json { render json: @hello.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hellos/1
  # DELETE /hellos/1.json
  def destroy
    @hello.destroy
    respond_to do |format|
      format.html { redirect_to hellos_url, notice: 'Hello was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hello
      @hello = Hello.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hello_params
      params.require(:hello).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hellos_helper.rb
module HellosHelper
end

app/views/hellos/_form.html.erb
<%= form_for(@hello) do |f| %>
  <% if @hello.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hello.errors.count, "error") %> prohibited this hello from being saved:</h2>

      <ul>
      <% @hello.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hellos/edit.html.erb
<h1>Editing hello</h1>

<%= render 'form' %>

<%= link_to 'Show', @hello %> |
<%= link_to 'Back', hellos_path %>

app/views/hellos/index.html.erb
<h1>Listing hellos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hellos.each do |hello| %>
      <tr>
        <td><%= hello.name %></td>
        <td><%= hello.address %></td>
        <td><%= link_to 'Show', hello %></td>
        <td><%= link_to 'Edit', edit_hello_path(hello) %></td>
        <td><%= link_to 'Destroy', hello, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hello', new_hello_path %>

app/views/hellos/new.html.erb
<h1>New hello</h1>

<%= render 'form' %>

<%= link_to 'Back', hellos_path %>

app/views/hellos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hello.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hello.address %>
</p>

<%= link_to 'Edit', edit_hello_path(@hello) %> |
<%= link_to 'Back', hellos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>